---
title: "Branches"
subtitle: "Exploring NCUA 5300 Call Reports: Part I"
author: '[Lawrence Chen](mailto:lawrence.chen@experian.com)'
date: '`r format(Sys.Date(), "%B %e, %Y")`'
output: html_notebook
---

```{r init, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.kable.NA = "")
```
```{r setup, message=FALSE}
library(zoo)
library(readxl)
library(data.table)
library(ggplot2)
library(tidyr)
library(plyr)
library(dplyr)
library(stringr)
library(knitr)
library(pander)

source("R/ncua.R")

srcDataDir <- file.path(getwd(), "1.SourceData")
ncuaDir <- file.path(srcDataDir, "ncua.gov")
```

\pagebreak

__*Abstract:*__ (WIP) # CU open branches and surviving insitutions over time 

---

Knitted with R version `r getRversion()` at `r Sys.time()`

Please contact <lawrence.chen@experian.com> for the source code and data used in this analysis.

\pagegreak

# Data

build a vector of call reports URLs and download from nuca.gov

5300 Call Report Account Descriptions

https://www.ncua.gov/regulation-supervision/Pages/documents/call-report-account-descriptions-9302017.pdf

```{r message=FALSE}
x <- seq(as.Date("1994-4-1"), as.Date("2017-7-1"), by = "3 months") - 1
y <- sapply(x, url.5300cr)

bad <- grep("QCR201306.zip", y)
y[bad] <- "https://www.ncua.gov/DataApps/Documents/5300Data0613Final.zip"

bad <- !file.exists(file.path(ncuaDir, basename(y)))
for(url in y[bad]) {
    download.5300cr(url)
}
```

```{r}
fns <- list.files(file.path(ncuaDir), "FOICU.txt", full.names = T, recursive = T, ignore.case = T)
foicu <- ldply(fns, read.5300cr)
setDT(foicu, key = "CU_NUMBER")
```

```{r}
ggplot(data =  foicu[month(CYCLE_DATE) == 6, uniqueN(CU_NUMBER), keyby = CYCLE_DATE],
       aes(x = CYCLE_DATE, y = V1)) +
    geom_line() +
    labs(title = "Number of Credit Unions")
```


```{r}
fns <- list.files(file.path(ncuaDir), "branch", full.names = T, recursive = T, ignore.case = T)
foicu.b <- ldply(fns, read.5300cr)
setDT(foicu.b, key = "CU_NUMBER")
```
```{r}
ggplot(data =  foicu.b[month(CYCLE_DATE) == 6, uniqueN(SiteId), keyby = CYCLE_DATE],
       aes(x = CYCLE_DATE, y = V1)) +
    geom_line() +
    labs(title = "Number of Credit Unions Branches")
```
```{r}
ggplot(data =  foicu.b[month(CYCLE_DATE) == 6, uniqueN(SiteId) / uniqueN(CU_NUMBER), keyby = CYCLE_DATE],
       aes(x = CYCLE_DATE, y = V1)) +
    geom_line() +
    labs(title = "Average Number of Branches")
```
